"""add company_name to employee_master

Revision ID: 210b4d35d739
Revises: 4a6c010b1a24
Create Date: 2026-07-28 07:06:37.177179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210b4d35d739'
down_revision: Union[str, None] = '4a6c010b1a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_master', sa.Column('company_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_master', 'company_name')
    # ### end Alembic commands ###
