"""add food_vector_source to menu_master

Revision ID: 2a034f9e204d
Revises: ad01a1068040
Create Date: 2026-07-28 08:49:39.898644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a034f9e204d'
down_revision: Union[str, None] = 'ad01a1068040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_master', sa.Column('food_vector_source', sa.Enum('규칙기반', 'LLM추정', '관리자수동', name='foodvectorsource', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_master', 'food_vector_source')
    # ### end Alembic commands ###
