"""initial schema

Revision ID: 4a6c010b1a24
Revises: 
Create Date: 2026-07-27 13:50:55.072733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4a6c010b1a24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector 확장 (menu_master.food_vector, employee_taste_profile.profile_vector,
    # meal_log.comment_embedding 컬럼에 필요) — PRD 9.3
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corner_master',
    sa.Column('corner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corner_name', sa.String(length=64), nullable=False),
    sa.Column('is_diet_corner', sa.Boolean(), nullable=False),
    sa.Column('avg_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('corner_id'),
    sa.UniqueConstraint('corner_name')
    )
    op.create_table('daily_division_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('division', sa.Enum('본사', '계열사', '기타', name='division', native_enum=False), nullable=False),
    sa.Column('meal_type', sa.Enum('조식', '중식', '석식', name='mealtype', native_enum=False), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'division', 'meal_type')
    )
    op.create_index(op.f('ix_daily_division_stats_stat_date'), 'daily_division_stats', ['stat_date'], unique=False)
    op.create_table('employee_master',
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('division', sa.Enum('본사', '계열사', '기타', name='division', native_enum=False), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('holiday_calendar',
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('holiday_type', sa.Enum('법정공휴일', '대체공휴일', '근로자의날', '회사자체휴무', name='holidaytype', native_enum=False), nullable=False),
    sa.Column('holiday_name', sa.String(length=64), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('calendar_date')
    )
    op.create_table('menu_master',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('food_vector', pgvector.sqlalchemy.vector.VECTOR(dim=10), nullable=True),
    sa.PrimaryKeyConstraint('menu_id'),
    sa.UniqueConstraint('menu_name')
    )
    op.create_table('monthly_voe_cluster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('cluster_label', sa.String(length=128), nullable=False),
    sa.Column('representative_comment', sa.Text(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_voe_cluster_period'), 'monthly_voe_cluster', ['period'], unique=False)
    op.create_table('congestion_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('corner_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('조식', '중식', '석식', name='mealtype', native_enum=False), nullable=False),
    sa.Column('time_bucket', sa.String(length=16), nullable=False),
    sa.Column('predicted_headcount', sa.Float(), nullable=False),
    sa.Column('predicted_wait_minutes', sa.Float(), nullable=True),
    sa.Column('scenario_tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['corner_id'], ['corner_master.corner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_congestion_forecast_corner_id'), 'congestion_forecast', ['corner_id'], unique=False)
    op.create_index(op.f('ix_congestion_forecast_forecast_date'), 'congestion_forecast', ['forecast_date'], unique=False)
    op.create_table('daily_corner_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('corner_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('조식', '중식', '석식', name='mealtype', native_enum=False), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('avg_taste_score', sa.Float(), nullable=True),
    sa.Column('peak_throughput_per_min', sa.Float(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['corner_id'], ['corner_master.corner_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'corner_id', 'meal_type')
    )
    op.create_index(op.f('ix_daily_corner_stats_corner_id'), 'daily_corner_stats', ['corner_id'], unique=False)
    op.create_index(op.f('ix_daily_corner_stats_stat_date'), 'daily_corner_stats', ['stat_date'], unique=False)
    op.create_table('employee_taste_profile',
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('profile_vector', pgvector.sqlalchemy.vector.VECTOR(dim=10), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_master.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('menu_performance_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('appearance_count', sa.Integer(), nullable=False),
    sa.Column('total_headcount', sa.Integer(), nullable=False),
    sa.Column('evaluation_count', sa.Integer(), nullable=False),
    sa.Column('evaluation_rate', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('adjusted_score', sa.Float(), nullable=True),
    sa.Column('share_of_traffic', sa.Float(), nullable=True),
    sa.Column('quadrant_label', sa.Enum('인기메뉴', '숨은강자', '개선시급', '퇴출후보', '표본부족', name='menuquadrant', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_master.menu_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', 'menu_id')
    )
    op.create_index(op.f('ix_menu_performance_stats_menu_id'), 'menu_performance_stats', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_performance_stats_period_end'), 'menu_performance_stats', ['period_end'], unique=False)
    op.create_index(op.f('ix_menu_performance_stats_period_start'), 'menu_performance_stats', ['period_start'], unique=False)
    op.create_table('weekly_menu_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('조식', '중식', '석식', name='mealtype', native_enum=False), nullable=False),
    sa.Column('corner_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('menu_role', sa.Enum('메인', '부찬', name='menurole', native_enum=False), nullable=False),
    sa.Column('is_new_menu', sa.Boolean(), nullable=False),
    sa.Column('source_row_raw', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['corner_id'], ['corner_master.corner_id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_master.menu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_menu_plan_corner_id'), 'weekly_menu_plan', ['corner_id'], unique=False)
    op.create_index(op.f('ix_weekly_menu_plan_menu_id'), 'weekly_menu_plan', ['menu_id'], unique=False)
    op.create_index(op.f('ix_weekly_menu_plan_plan_date'), 'weekly_menu_plan', ['plan_date'], unique=False)
    op.create_table('meal_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('meal_type', sa.Enum('조식', '중식', '석식', name='mealtype', native_enum=False), nullable=False),
    sa.Column('corner_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('taste_score', sa.Enum('개선', '보통', '맛남', name='tastescore', native_enum=False), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('comment_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('menu_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corner_id'], ['corner_master.corner_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_master.employee_id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_master.menu_id'], ),
    sa.ForeignKeyConstraint(['menu_snapshot_id'], ['weekly_menu_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_log_corner_id'), 'meal_log', ['corner_id'], unique=False)
    op.create_index(op.f('ix_meal_log_eaten_at'), 'meal_log', ['eaten_at'], unique=False)
    op.create_index(op.f('ix_meal_log_employee_id'), 'meal_log', ['employee_id'], unique=False)
    op.create_index(op.f('ix_meal_log_menu_id'), 'meal_log', ['menu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_log_menu_id'), table_name='meal_log')
    op.drop_index(op.f('ix_meal_log_employee_id'), table_name='meal_log')
    op.drop_index(op.f('ix_meal_log_eaten_at'), table_name='meal_log')
    op.drop_index(op.f('ix_meal_log_corner_id'), table_name='meal_log')
    op.drop_table('meal_log')
    op.drop_index(op.f('ix_weekly_menu_plan_plan_date'), table_name='weekly_menu_plan')
    op.drop_index(op.f('ix_weekly_menu_plan_menu_id'), table_name='weekly_menu_plan')
    op.drop_index(op.f('ix_weekly_menu_plan_corner_id'), table_name='weekly_menu_plan')
    op.drop_table('weekly_menu_plan')
    op.drop_index(op.f('ix_menu_performance_stats_period_start'), table_name='menu_performance_stats')
    op.drop_index(op.f('ix_menu_performance_stats_period_end'), table_name='menu_performance_stats')
    op.drop_index(op.f('ix_menu_performance_stats_menu_id'), table_name='menu_performance_stats')
    op.drop_table('menu_performance_stats')
    op.drop_table('employee_taste_profile')
    op.drop_index(op.f('ix_daily_corner_stats_stat_date'), table_name='daily_corner_stats')
    op.drop_index(op.f('ix_daily_corner_stats_corner_id'), table_name='daily_corner_stats')
    op.drop_table('daily_corner_stats')
    op.drop_index(op.f('ix_congestion_forecast_forecast_date'), table_name='congestion_forecast')
    op.drop_index(op.f('ix_congestion_forecast_corner_id'), table_name='congestion_forecast')
    op.drop_table('congestion_forecast')
    op.drop_index(op.f('ix_monthly_voe_cluster_period'), table_name='monthly_voe_cluster')
    op.drop_table('monthly_voe_cluster')
    op.drop_table('menu_master')
    op.drop_table('holiday_calendar')
    op.drop_table('employee_master')
    op.drop_index(op.f('ix_daily_division_stats_stat_date'), table_name='daily_division_stats')
    op.drop_table('daily_division_stats')
    op.drop_table('corner_master')
    # ### end Alembic commands ###
    # 주의: vector 확장은 여기서 DROP하지 않는다 — 확장 소유권이 DB 생성 계정과
    # 다를 수 있고(superuser로 생성한 경우 등), 다른 스키마가 의존할 수도 있어
    # 확장 제거는 DBA가 별도로 판단하도록 남겨둔다.
