"""add taste_cluster table and employee_taste_profile.cluster_id

Revision ID: ad01a1068040
Revises: 210b4d35d739
Create Date: 2026-07-28 07:31:56.807409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ad01a1068040'
down_revision: Union[str, None] = '210b4d35d739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_FK_NAME = "fk_employee_taste_profile_cluster_id_taste_cluster"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taste_cluster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('cluster_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('centroid_vector', pgvector.sqlalchemy.vector.VECTOR(dim=10), nullable=False),
    sa.Column('avg_satisfaction', sa.Float(), nullable=True),
    sa.Column('top_menus', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('dominant_corner', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employee_taste_profile', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(_FK_NAME, 'employee_taste_profile', 'taste_cluster', ['cluster_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(_FK_NAME, 'employee_taste_profile', type_='foreignkey')
    op.drop_column('employee_taste_profile', 'cluster_id')
    op.drop_table('taste_cluster')
    # ### end Alembic commands ###
